### ISSUE TITLE
'AttributeError: module 'azure.core.pipeline.policies' has no attribute 'SensitiveHeaderCleanupPolicy''.

### ISSUE THREAD

**Issue by hchitnen** [Azure/azure-sdk-for-python#34880]
**Describe the bug**
The above error is throwing up when running the below code. To be specific, this happens when calling the 'ImageAnalysisClient'
I have the azure-core 1.30 version (the latest) but still receiving the error. 

** Code To Reproduce**

import pandas as pd
import os
from azure.ai.vision.imageanalysis import ImageAnalysisClient
from azure.ai.vision.imageanalysis.models import VisualFeatures
from azure.core.credentials import AzureKeyCredential
import numpy as np

def azureml_main(dataframe1 = None, dataframe2 = None):

    # Execution logic goes here
    print(f'Input pandas.DataFrame #1: {dataframe1}')

    client = ImageAnalysisClient(
    endpoint='https://ipmicro-ocr.cognitiveservices.azure.com/',
    credential=AzureKeyCredential('<redacted>')
    )

# Get a caption for the image. 

    for i in range(0,5):
        result = client.analyze_from_url(
            image_url=products['ItemDocumentValue'][i],
            visual_features=[VisualFeatures.CAPTION, VisualFeatures.READ, VisualFeatures.TAGS],
            gender_neutral_caption=True,  # Optional (default is False)
        )

        print("Image analysis results:")
        # Print caption results to the console
        print(" Caption:")
        if result.caption is not None:
            print(f"   '{result.caption.text}', Confidence {result.caption.confidence:.4f}")
            products['Caption'][i] = result.caption.text

        if result.tags is not None:
            print(" Tags:")
            temp_tags=[]
            for tag in result.tags.list:
                print(f"   '{tag.name}', Confidence {tag.confidence:.4f}")
                temp_tags.append(tag.name)
            products['Tags'][i] = temp_tags  

        # Print text (OCR) analysis results to the console
        print(" Read:")
        if result.read is not None:
            temp_des=''
            try:
                for line in result.read.blocks[0].lines:
                    temp_des = temp_des + ' '+ line.text
                products['Description'][i] = temp_des
            except:
                np.nan
    return products,

**Exact Error:** 

---------- Start of error message from Python interpreter ----------
Got exception when invoking script at line 22 in function azureml_main: 'AttributeError: module 'azure.core.pipeline.policies' has no attribute 'SensitiveHeaderCleanupPolicy''.
---------- End of error message from Python  interpreter  ----------

**Comment by xiangyan99** [comment]
Thanks for reaching out.

Could you run pip list and share the output?

**Comment by hchitnen** [comment]
Please do let me know in case any further information is needed from my end.

**Comment by hchitnen** [comment]
Hi, any update?

**Comment by dargilco** [comment]
@hchitnen do the samples in this link work for you using the same credentials you used above? 
https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/vision/azure-ai-vision-imageanalysis/samples

**Comment by newhardwarefound** [comment]
I am having the same issue. The code works on Python 3.11 but not on Python 3.8. They seem to have exactly the same environment.

**Comment by pacozaa** [comment]
That isn't nice. Some libraries need Python 3.10 like Unsloth. It doesn't make any sense that this error has not been fix given the cost of GPU VM.

**Comment by noe-sautel** [comment]
Hello @dargilco, any update on this? I have a similar issue

**Comment by pranav-thampi-numerator** [comment]
I am getting the same error while trying the create a cron-job-schedule using
az ml schedule create --file {file_name} --debug --resource-group {rsg_name} --workspace-name {workspace-name}

here is the error:

`Traceback (most recent call last):
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_operation_orchestrator.py", line 279, in _get_code_asset_arm_id
    code_asset = self._code_assets.create_or_update(code_asset)  # type: ignore[attr-defined]
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_telemetry/activity.py", line 288, in wrapper
    return f(*args, **kwargs)
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_code_operations.py", line 212, in create_or_update
    raise ex
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/operations/_code_operations.py", line 160, in create_or_update
    code, _ = _check_and_upload_path(
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_artifacts/_artifact_utilities.py", line 502, in _check_and_upload_path
    uploaded_artifact = _upload_to_datastore(
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_artifacts/_artifact_utilities.py", line 387, in _upload_to_datastore
    artifact = upload_artifact(
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_artifacts/_artifact_utilities.py", line 240, in upload_artifact
    storage_client = get_storage_client(credential=None, storage_account=None, account_url=sas_uri)
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_utils/_storage_utils.py", line 177, in get_storage_client
    return client_builders[storage_type](credential, container_name, account_url)
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_utils/_storage_utils.py", line 151, in <lambda>
    DatastoreType.AZURE_BLOB: lambda credential, container_name, account_url: BlobStorageClient(
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azext_mlv2/manual/vendored_curated_sdk/azure/ai/ml/_artifacts/_blob_storage_helper.py", line 50, in __init__
    self.service_client = BlobServiceClient(account_url=account_url, credential=credential)
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azure/storage/blob/_blob_service_client.py", line 141, in __init__
    self._client = AzureBlobStorage(self.url, base_url=self.url, pipeline=self._pipeline)
  File "/agent/_work/_temp/.azclitask/cliextensions/ml/azure/storage/blob/_generated/_azure_blob_storage.py", line 72, in __init__
    policies.SensitiveHeaderCleanupPolicy(**kwargs) if self._config.redirect_policy else None,
AttributeError: module 'azure.core.pipeline.policies' has no attribute 'SensitiveHeaderCleanupPolicy'
`

**Comment by pranav-thampi-numerator** [comment]
It worked for me by upgarding the version of azure-cli
https://github.com/Azure/azure-cli/issues/28649

**Comment by hchitnen** [comment]
I deleted the 'SensitiveHeaderCleanupPolicy' class dependency from the package and it worked for me. although, not sure about the ramifications of this action. Worked for my use case.

**Comment by ptsapralis** [comment]
This https://github.com/Azure/azure-sdk-for-python/issues/34091#issuecomment-2167676966 worked for me (thank you https://github.com/dnzau).

**Comment by dargilco** [comment]
Hi all, I released beta 3 of the Image Analysis package with updated dependencies. Resolving this issue. If you still see this issue with the new package, please reactivate and tag me. Thanks!
