### ISSUE TITLE
Async azure-servicebus 0.50.x, 0.21.x broken on Python 3.6 - asyncio has no attribute get_running_loop

### ISSUE THREAD

**Issue by rringham** [Azure/azure-sdk-for-python#10436]
- **Package Name**: azure.servicebus
- **Package Version**: 0.50.2, 0.50.1, 0.50.0, 0.21.1
- **Operating System**: Ubuntu 18.04 LTS
- **Python Version**: 3.6.9

**Describe the bug**
`AttributeError: module 'asyncio' has no attribute 'get_running_loop'` as soon as you call `ServiceBusClient.from_connection_string`.

This is what you get, instantly:

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/azure/servicebus/common/utils.py", line 27, in get_running_loop
    return asyncio.get_running_loop()
AttributeError: module 'asyncio' has no attribute 'get_running_loop'`

**To Reproduce**
1. Run Python 3.6
2. Run this code:
`from azure.servicebus.aio import ServiceBusClient`
`connection_str = 'MY_CONNECTION_STRING'`
`sb_client = ServiceBusClient.from_connection_string(connection_str)`

**Expected behavior**
Per the documentation that indicates "The client libraries are supported on Python 2.7 and 3.5.3 or later.", this should work on Python 3.6.9.

Needing to upgrade to Python 3.7 is not a reasonable or viable option.

**Comment by kaerm** [comment]
@rringham thanks for reporting this, someone from our team will take a look at this //cc: @mayurid, @KieranBrantnerMagee

**Comment by yunhaoling** [comment]
Hello @rringham ,

The code: `sb_client = ServiceBusClient.from_connection_string(connection_str)` should be called inside a coroutine like:

```python
import asyncio

async def main():
    sb_client = ServiceBusClient.from_connection_string(connection_str)
    # more code
```

More async samples could be found here: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/servicebus/azure-servicebus/samples/async_samples

In async world, the ServiceBusClient needs to get an event loop prepared for further async operations. In this case, an event loop can only be got when the code is running in coroutine.

Let me know whether this helps solve your problem or not.

**Comment by yunhaoling** [comment]
Hi @rringham , does this solve your problem?

**Comment by yunhaoling** [comment]
I'm closing this assuming the issue has already been resolved.
Feel free to re-open if further help is needed.
