### PR TITLE
[Service Bus] Fix batch send of messages with routing properties

### PR DESCRIPTION
**Pull request by EldertGrootenboer**
## Problem

Sending a **batch** of messages with `message_id`, `session_id`, or
`partition_key` set on the first message raised
`TypeError: 'BatchMessage' object is not subscriptable` under the **uamqp**
transport (`uamqp_transport=True`), and surfaced a secondary
`AttributeError: 'list' object has no attribute '_message'` on the list send
path. Regression from #42598.

Root cause: `ServiceBusMessageBatch._add` captured the batch-envelope
`message_id`/`session_id` properties and `partition_key` annotation by calling
the module-level **pyamqp** helpers (`set_message_properties` /
`set_message_annotations`) unconditionally, regardless of the active transport.
Those helpers index the message as a list (`message[3]`, `message[2]`). Under
uamqp the batch envelope is a `BatchMessage` (not subscriptable), so the
capture raised `TypeError`.

One root cause, two symptoms:

- **Batch-object path** (`create_message_batch()` + `add_message()`): the
  `TypeError` surfaces directly.
- **List path** (`send_messages([...])`): the sender builds a batch via
  `_from_list()` -> `_add()`; the same `TypeError` was then swallowed by a
  broad `except TypeError` (intended to detect "not a list"), which went on to
  do `obj_message._message = ...` on the list, producing the reported secondary
  `AttributeError`.

Under uamqp the outgoing transform auto-assigns a `message_id`, so even a bare
`ServiceBusMessage(b"x")` in a batch triggered the crash.

## Fix

- Move batch-envelope property capture behind a new transport method,
  `set_batch_envelope_properties(batch_message, message_id, session_id,
  partition_key)`, with separate pyamqp and uamqp implementations. The pyamqp
  implementation preserves the existing list-indexed behavior; the uamqp
  implementation sets `batch_message.properties = MessageProperties(...)` plus
  the partition-key annotation. It is a no-op when all three are falsy and runs
  once per batch.
- Call it once per batch from `_common/message.py` (guarded by
  `self._count == 1`), and drop the now-unused unconditional pyamqp import.
- Replace the broad `except TypeError` in the sync and async senders with an
  explicit `isinstance(obj_message, list)` check, so a genuine `TypeError`
  raised while building the batch is no longer masked.
  `transform_outbound_messages` returns a list for iterable input and a single
  `ServiceBusMessage` otherwise, so the discrimination is behavior-equivalent
  for valid inputs.

Routing-property mapping is consistent with the other Azure SDK languages:
`session_id` maps to the AMQP `group-id`, `partition_key` to the
`x-opt-partition-key` annotation.

## Testing

Added unit coverage in `tests/test_message.py`:

- `test_set_batch_envelope_properties` exercises each branch (no-op,
  message_id only, session_id only, partition_key only) on both transports.
- strengthened `test_servicebus_message_batch` to assert the envelope
  properties and annotations on both transports.
- `test_transform_outbound_messages_discriminates_list_vs_single` pins the
  list-vs-single contract the sender discrimination relies on.

Result (Python 3.12): targeted run `5 passed`. Batch and send behavior across
both transports is additionally covered by the live `test_queues` /
`test_queues_async` suites.

## What changed

- `sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_base.py`
- `sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_pyamqp_transport.py`
- `sdk/servicebus/azure-servicebus/azure/servicebus/_transport/_uamqp_transport.py`
- `sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py`
- `sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_sender.py`
- `sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_sender_async.py`
- `sdk/servicebus/azure-servicebus/tests/test_message.py`
- `sdk/servicebus/azure-servicebus/CHANGELOG.md`

### CODE REVIEW

**Review by j7nw4r — APPROVED** [review]
LGTM
