### ISSUE TITLE
DNS Issue while connecting to azure configuration manager

### ISSUE THREAD

**Issue by erbek** [Azure/azure-sdk-for-python#37773]
- **Package Name**:  azure.appconfiguration.provider
- **Package Version**: 2.0.0b1
- **Operating System**: windows
- **Python Version**:  3.11.4
- **dnspython version**: 2.7.0

**Describe the bug**
While loading configuration settings i got dns problem:
![image](https://github.com/user-attachments/assets/16a7428c-bae4-4853-94b5-b2b88b2a34a8)

Line 36 causes the error, while line 37 is executed ok.
I don't have this issue using azure.appconfiguration.provider version: 1.0.0

**To Reproduce**
1. Just connect to appservice configuration manager using the connection_string

**Expected behavior**
Expected behavior is to receive configuration entries - it works fine in version 1.0.0 for me - however I need refresh feature

**Screenshots**

**Additional context**

E           dns.resolver.LifetimeTimeout: The resolution lifetime expired after 5.132 seconds: Server Do53:8.8.8.8@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.4.4@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.96.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.99.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.8.8@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.4.4@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.96.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.99.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.8.8@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.4.4@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.96.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.99.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.8.8@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.4.4@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.96.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.99.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.8.8@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.4.4@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.96.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.99.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.8.8@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:8.8.4.4@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.96.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'; Server Do53:103.86.99.100@53 answered udp() got an unexpected keyword argument 'ignore_errors'

c:\Users\rafal\AppData\Local\Programs\Python\Python311\Lib\site-packages\dns\resolver.py:1076: LifetimeTimeout
====================================================================================================== warnings s

**Comment by erbek** [comment]
Hello team
any idea?

**Comment by erbek** [comment]
The solution was to upgrade eventlet to 0.36.1 - previous version was 0.33.0

**Comment by mrm9084** [comment]
@erbek, good to know. Also, you should look into using 1.3.0, currently the 2.0.0b1 release is to support telemetry with App Insights when using feature flags with our feature management library.

**Comment by erbek** [comment]
Thanks
What about refresh? Isn’t that only supported by >=2.0?

W dniu czw., 10 paź 2024 o 19:04 Matthew Metcalf ***@***.***>
napisał(a):

**Comment by mrm9084** [comment]
That was part of the 1.1.0 release https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/AzureAppConfigurationProviderPython.md#110---january-29-2024.

**Comment by erbek** [comment]
Ok, thanks for the clarification.

W dniu czw., 10 paź 2024 o 19:14 Matthew Metcalf ***@***.***>
napisał(a):
