### ISSUE TITLE
DataFactoryManagementClient does not work in azure-mgmt-datafactory-1.0.0

### ISSUE THREAD

**Issue by mattiethecat** [Azure/azure-sdk-for-python#16017]
- **Package Name**: azure-mgmt-datafactory
- **Package Version**:  1.0.0
- **Operating System**: Windows 10
- **Python Version**:  3.6.8 and 3.7.4

**Describe the bug**
In the 1.0.0 release, azure-mgmt-datafactory has this error:

Exception has occurred: AttributeError
'ServicePrincipalCredentials' object has no attribute 'get_token'  

**To Reproduce**

 _Install the following:_
conda create --yes --quiet --name myEnvironment3 python=3.6.8
call activate myEnvironment3
pip install azure-mgmt-datafactory==1.0.0
pip install msrestazure

Create a python file and execute it:

from azure.mgmt.datafactory import DataFactoryManagementClient
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.datafactory.models import Dataset, PipelineResource

df_name = '...' 
rg_name = '...' 
client_id= '...' 
client_secret='...' 
tenant_id ='...' 
subscription_id = '...' 

credentials = ServicePrincipalCredentials(client_id=client_id, secret=client_secret, tenant=tenant_id)
adf_client = DataFactoryManagementClient(credentials, subscription_id)
dflist = adf_client.factories.list_by_resource_group(rg_name)
for i in dflist:
    print (i)

**Expected behavior**
A list of data factories
. Error can be avoided by changing the above pip install step to be: pip install azure-mgmt-datafactory==0.14.0

**Comment by RazvanMorarescu** [comment]
Hi,
I had the same issue today, but when triggering an ADF Pipeline.

I found a workaround and these are the changes i made:
1.  Install azure-identity
2.  Instead ServicePrincipalCredentials use ClientSecretCredential 
`from azure.mgmt.datafactory import DataFactoryManagementClient`
`from azure.identity import ClientSecretCredential`
`credentials = ClientSecretCredential(client_id=client_id, client_secret=client_secret, tenant_id=tenant_id)`
`adf_client = DataFactoryManagementClient(credentials, subscription_id)`

Hope this helps :)

Also this is the full list of packages i used:
    - azure-common==1.1.26
    - azure-core==1.9.0
    - azure-identity==1.5.0
    - azure-mgmt-core==1.2.2
    - azure-mgmt-datafactory==1.0.0
    - msal==1.8.0
    - msal-extensions==0.3.0
    - msrest==0.6.19
    - msrestazure==0.6.4

**Comment by 00Kai0** [comment]
Hi @mattiethecat ,
This package `azure-mgmt-datafactory` with version `1.0.0` is created by the next-generation code generator that has lots of importtant breaking changes.
You can follow this [migration guide](https://github.com/Azure/azure-sdk-for-python/blob/master/doc/sphinx/python_mgmt_migration_guide.rst) to fix your code. 
If you don't want to use this new version now, you just need to keep verion < `1.0.0`.
