### ISSUE TITLE
Iteration over ContainerClient.list_blobs() raises an exception `AttributeError: 'NoneType' object has no attribute 'blob_items'`

### ISSUE THREAD

**Issue by psihonavt** [Azure/azure-sdk-for-python#29719]
- azure-storage-blob
- 12.15.0 
- CentOS 8
- 3.9.12

**Describe the bug**
Attempt to iterate over blobs in a container raises AttributeError.
Iterating over blob names with the same client works as expected.

**To Reproduce**
```
sas_token = generate_container_sas(
            account_name=self._account_name,
            account_key=self._account_key,
            permission=ContainerSasPermissions(read=True, write=True, delete=True, list=True),
            container_name="57a3d709e482984e56b89f1a",
            expiry=datetime.utcnow() + timedelta(hours=2)
        )
client = ContainerClient(account_url=..., credential=sas_token, container_name='57a3d709e482984e56b89f1a')

In [28]: next(client.list_blobs())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-cac8b16242a6> in <module>
----> 1 next(client.list_blobs())

/media/ephemeral0/nimble/runtime/lib/python3.9/site-packages/azure/core/paging.py in __next__(self)
    126         if self._page_iterator is None:
    127             self._page_iterator = itertools.chain.from_iterable(self.by_page())
--> 128         return next(self._page_iterator)
    129
    130     next = __next__  # Python 2 compatibility.

/media/ephemeral0/nimble/runtime/lib/python3.9/site-packages/azure/core/paging.py in __next__(self)
     82         self._did_a_call_already = True
     83
---> 84         self.continuation_token, self._current_page = self._extract_data(self._response)
     85
     86         return iter(self._current_page)

/media/ephemeral0/nimble/runtime/lib/python3.9/site-packages/azure/storage/blob/_list_blobs_helper.py in _extract_data_cb(self, get_next_return)
    107         self.results_per_page = self._response.max_results
    108         self.container = self._response.container_name
--> 109         self.current_page = [self._build_item(item) for item in self._response.segment.blob_items]
    110
    111         return self._response.next_marker or None, self.current_page

AttributeError: 'NoneType' object has no attribute 'blob_items'


In [29]: next(client.list_blob_names())
Out[29]: '001f26a9049c5ef1e2d6b153b5d9f3e1'
```

**Expected behavior**
The container client should iterate over its blobs without raising exceptions. 

UPDATE:
`list_blobs` works with with a SDK version `12.13.1`

**Comment by tjprescott** [comment]
@psihonavt are you saying that you updated your blobs SDK and now it works?

**Comment by psihonavt** [comment]
Yes, the downgrade from 12.15.0 to 12.13.1 helped (all PyPI-available versions higher than 12.13.1 have this bug too).

**Comment by tjprescott** [comment]
@jalauzon-msft this appears to be a regression in the storage-blob SDK. Can you please take a look?

**Comment by vincenttran-msft** [comment]
Hi @psihonavt Anton, thanks for your inquiry. I was unable to reproduce your findings locally, and attached below is what I used to attempt to reproduce your issue:
```
from azure.storage.blob import generate_container_sas, ContainerSasPermissions, ContainerClient
from datetime import datetime, timedelta

ACCOUNT_URL = f"https://<account_name>.blob.core.windows.net"
ACCOUNT_NAME = "<account_name>"
ACCOUNT_KEY = "<account_key>"

sas_token = generate_container_sas(
            account_name=ACCOUNT_NAME,
            account_key=ACCOUNT_KEY,
            permission=ContainerSasPermissions(read=True, write=True, delete=True, list=True),
            container_name="<container_name>",
            expiry=datetime.utcnow() + timedelta(hours=2)
        )

container_client = ContainerClient(account_url=ACCOUNT_URL, credential=sas_token, container_name="<container_name>")

# Single Iteration
ret = next(container_client.list_blobs())
print(ret, '\n')

# Full List Iteration
for b in container_client.list_blobs():
    print(b.name)
```
For reference, I was using the latest package version (12.15.0) for `azure-storage-blob`. and Python version 3.10.9

With that being said, some general tips that may be the cause of your issue:

- Check your SAS permissions, as maybe you don't have the proper permissions and so that is the source of the `None` type that is being accessed
- Consider using a `for` loop to iterate through the generator returned by the list_blobs API

If none of this seems to resolve your issue, could you please provide a more complete code snippet (with sensitive information redacted) in order for us to be able to continue to assist you.

Thanks!

**Comment by psihonavt** [comment]
@vincenttran-msft I pinned down the problem, but I wonder if it'll help you.

the next code works (not the line with `from nimble_core.application import CONFIGURATION`)
```
import sys
from datetime import datetime, timedelta

from azure.storage.blob import generate_account_sas, AccountSasPermissions, ResourceTypes, BlobServiceClient
from nimble_core.application import CONFIGURATION


ACCOUNT_NAME = "xxxxxx"
ACCOUNT_KEY = "xxxxxx"
ACCOUNT_URL = "https://{}.blob.core.windows.net".format(ACCOUNT_NAME)
CONTAINER_NAME = "57a3d709e482984e56b89f1a"

service_sas_token = generate_account_sas(
    account_name=ACCOUNT_NAME, account_key=ACCOUNT_KEY,
    permission=AccountSasPermissions(read=True, write=True, list=True, delete=True, create=True, add=True),
    expiry=datetime.utcnow() + timedelta(hours=2),
    resource_types=ResourceTypes(container=True, object=True, service=True)
)
service_client = BlobServiceClient(account_url=ACCOUNT_URL, credential=service_sas_token)

container_client = service_client.get_container_client(CONTAINER_NAME)

# Single Iteration
ret = next(container_client.list_blobs())
print(ret, '\n')
```

But when I change the import order to 
```
from nimble_core.application import CONFIGURATION
from azure.storage.blob import generate_account_sas, AccountSasPermissions, ResourceTypes, BlobServiceClient
```
, the exception comes back
```
Traceback (most recent call last):
  File "/tmp/asb-working.py", line 24, in <module>
    ret = next(container_client.list_blobs())
  File "/media/ephemeral0/nimble/runtime/lib/python3.9/site-packages/azure/core/paging.py", line 128, in __next__
    return next(self._page_iterator)
  File "/media/ephemeral0/nimble/runtime/lib/python3.9/site-packages/azure/core/paging.py", line 84, in __next__
    self.continuation_token, self._current_page = self._extract_data(self._response)
  File "/media/ephemeral0/nimble/runtime/lib/python3.9/site-packages/azure/storage/blob/_list_blobs_helper.py", line 109, in _extract_data_cb
    self.current_page = [self._build_item(item) for item in self._response.segment.blob_items]
AttributeError: 'NoneType' object has no attribute 'blob_items'
```

The line `from nimble_core.application import CONFIGURATION` triggers the import of all our 3rd party modules:
```
In [1]: import sys
In [2]: len(sys.modules)
Out[2]: 4442
```

Obviously, too many modules to look through. But if it helps – with azure-storage-blob==12.13.1, the import order doesn't cause this exception.

**Comment by lmazuel** [comment]
Hi @psihonavt 
While I'm not expert in storage SDK, I was curious to take a look and wasn't able to reproduce it either. Nor I was able to find what is `nimble_core` to help reproduce it. Can you list the total set of packages installed in your environment? I wonder if that's not something else not mentioned here that triggers the issue. For instance, storage packages used to have a `azure-storage-common`, that may create issues like this if loaded at the same time. A simple `pip list` would do. Thanks.

**Comment by psihonavt** [comment]
@lmazuel , `nimble_core` is one of our internal packages. Please find the list of packages here https://gist.github.com/psihonavt/a63c621fb9b16f635f73b174072ada95. If it helps, I think I can dump the contents of the `sys.modules`.

**Comment by lmazuel** [comment]
@psihonavt that's what I was curious to see, if you had `azure-storage-common` installed. This package may create conflicts with packages like `azure-storage-blob`. You shouln't have this package installed, no packages I see in your list should depend on it. If you have an hard coded list of packages to install, can you remove this one and retry?

**Comment by psihonavt** [comment]
@lmazuel, you're right – removing the `azure-storage-common` package made the error go away. Thank you!
