### ISSUE TITLE
Version 20.1.0 of azure-mgmt-resource breaks PolicyClient

### ISSUE THREAD

**Issue by josvo** [Azure/azure-sdk-for-python#23494]
- **azure-mgmt-resource**: 
- **20.1.0**: 
- **Linux**:
- **3.9**: 

**Describe the bug**
When executing the PolicyClient Python example from the MS Website, it works with `azure-mgmt-resource` `20.0.0`, but returns an error with version `20.1.0`:
AttributeError: 'NoneType' object has no attribute 'format'

**To Reproduce**
1. Execute the example provided at: https://docs.microsoft.com/en-us/azure/governance/policy/assign-policy-python
2. It works with version 20.0.0
3. It fails with version 20.1.0: `AttributeError: 'NoneType' object has no attribute 'format'`

**Expected behavior**
The new version is not expected to break the current behavior.

The release history doesn't show that there were changes regarding this matter: https://pypi.org/project/azure-mgmt-resource/20.1.0/

**Comment by xiangyan99** [comment]
Thanks for the feedback, we’ll investigate asap.

**Comment by msyyc** [comment]
Hi @josvo , I can't reproduce the error. Could you follow the [doc](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/debug_guide.md) to provide more detailed log?(please conceal  sensitive info)

**Comment by josvo** [comment]
Hi @msyyc 
This is strange, I cannot reproduce this behavior anymore. I tried with different Python versions and also different library versions, they all seem to work fine now.
I'm going to close this issue. In case I run into the problem again, I will reopen this bug report and provide the debug information. 
Thanks for your efforts.

**Comment by josvo** [comment]
Hi @msyyc 
Was able to reproduce it now. This is what I get:

```shell
cd /home/josef/vscode/azure-mgmt-resource ; /usr/bin/env /home/josef/vscode/azure-mgmt-resource/.venv/bin/python /home/josef/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/launcher 33557 -- /home/josef/vscode/azure-mgmt-resource/test.py 
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/josef/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/josef/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/josef/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib64/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/josef/vscode/azure-mgmt-resource/test.py", line 33, in <module>
    policyAssignment = policyClient.policy_assignments.create("/subscriptions/eb74d967-xxxx-xxxx-xxxx-xxxxx", "audit-vm-manageddisks", policyAssignmentDetails)
  File "/home/josef/vscode/azure-mgmt-resource/.venv/lib64/python3.9/site-packages/azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/josef/vscode/azure-mgmt-resource/.venv/lib64/python3.9/site-packages/azure/mgmt/resource/policy/v2021_06_01/operations/_policy_assignments_operations.py", line 614, in create
    request.url = self._client.format_url(request.url)
  File "/home/josef/vscode/azure-mgmt-resource/.venv/lib64/python3.9/site-packages/azure/core/pipeline/transport/_base.py", line 582, in format_url
    base = self._base_url.format(**kwargs).rstrip("/")
AttributeError: 'NoneType' object has no attribute 'format'
```
The code I use to create the PolicyAssignment:
```python
assignmentLocation = "westeurope"
policyAssignmentIdentity = Identity(type="SystemAssigned")
policyAssignmentDetails = PolicyAssignment(display_name="Audit VMs without managed disks Assignment", policy_definition_id="/providers/Microsoft.Authorization/policyDefinitions/06a78e20-9358-41c9-923c-fb736d382a4d", description="Shows all virtual machines not using managed disks", identity=policyAssignmentIdentity, location=assignmentLocation)

# Create new policy assignment
policyAssignment = policyClient.policy_assignments.create("/subscriptions/eb74d967-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "audit-vm-manageddisks", policyAssignmentDetails)
```

As before, this works perfectly with version 20.0.0, but doesn't with 20.1.0 and also not with 20.1.0.

**Comment by BigCat20196** [comment]
Hi @josvo, there may be a problem with the parameter format. Here is a [sample](https://github.com/Azure-Samples/azure-samples-python-management/blob/main/samples/resources/manage_resource_policy.py) fyi, it could work well in 20.0.0 or 21.0.0.

**Comment by josvo** [comment]
Hi
Found the time to test it:
The example provided at [Microsoft docs](https://docs.microsoft.com/en-us/azure/governance/policy/assign-policy-python) uses:
```python
policyClient = PolicyClient(credential, subId, base_url=none)
```
whereas your sample uses:
```python
    policy_client = PolicyClient(
        credential=DefaultAzureCredential(),
        subscription_id=SUBSCRIPTION_ID
    )
```

It turns out the behavior in _policy_client.py changed from using `base_url=None` to `base_url="https://management.azure.com"`.
See [this](https://github.com/Azure/azure-sdk-for-python/pull/22748/files#diff-63354bd18012d75e92a869d0707972b511ffe146190d2a671814041066c4da4f) commit. 
The solution is to leave away the `base_url` when creating a PolicyClient.
However, the documentation did not catch up with that change.
