### ISSUE TITLE
 from azure.cognitiveservices.vision.computervision.models import TextOperationStatusCodes fails with version 0.6.0

### ISSUE THREAD

**Issue by Santhosh-KS** [Azure/azure-sdk-for-python#11656]
- **Package Name**: 
```python
from azure.cognitiveservices.vision.computervision.models import TextOperationStatusCodes
```
- **Package Version**: 
`0.6.0`
- **Operating System**:
`Linux` and `Windows`, Installing Azure dependencies using anaconda and virtual environment
- **Python Version**: 
`3.6` and `3.8`

**Describe the bug**
```sh
$ python3.6
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.cognitiveservices.vision.computervision.models import TextOperationStatusCodes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TextOperationStatusCodes'
```

**To Reproduce**
1. Install anaconda using the steps [here](https://www.digitalocean.com/community/tutorials/how-to-install-the-anaconda-python-distribution-on-ubuntu-18-04) 
2. pip install azure-cognitiveservices-vision-computervision
3. try to import it in the python throws the error as shown above.

**Expected behavior**
Should be able to include the following package as in version 0.5.0
 from azure.cognitiveservices.vision.computervision.models import TextOperationStatusCodes

**Additional context**
This module inclusion was working in 0.5.0. And the examples were working expected aswel. If there is any change in the module inclusion hierarchy, needs to updated in the document.

**Comment by lmazuel** [comment]
Hi @Santhosh-KS 
This doesn't exist anymore indeed, and the main Readme of the package has been updated:
https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision

What document are you referring?

**Comment by Santhosh-KS** [comment]
Hi Imazule,

I am using the documentation provided in this official guide.

https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/client-library?pivots=programming-language-python

I use the official release pypi installation approach.

https://pypi.org/project/azure-cognitiveservices-vision-computervision/

```sh
pip install azure-cognitiveservices-vision-computervision
```

and try to import

```python
from azure.cognitiveservices.vision.computervision import ComputerVisionClient
from azure.cognitiveservices.vision.computervision.models import TextOperationStatusCodes
from azure.cognitiveservices.vision.computervision.models import TextRecognitionMode
from azure.cognitiveservices.vision.computervision.models import VisualFeatureTypes
from msrest.authentication import CognitiveServicesCredentials

from array import array
import os
from PIL import Image
import sys
import time
```
I get the error

```sh
from azure.cognitiveservices.vision.computervision.models import TextOperationStatusCodes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TextOperationStatusCodes'
```

Where as if I install the version `0.5.0` I don't get the error.

```sh
pip install azure-cognitiveservices-vision-computervision==0.5.0
```

**Comment by lmazuel** [comment]
Thanks for the pointer, it helps to know what to update :)
In the meantime, the PyPI front page was updated:
https://pypi.org/project/azure-cognitiveservices-vision-computervision/

Assigning right team, thanks!

**Comment by asheeshmathur** [comment]
Any update or fix for this issue

**Comment by ryogok** [comment]
TextOperationStatusCodes is not available in 0.6.0 library anymore, and the documentation including the [Quickstart ](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/client-library?pivots=programming-language-python)page for Python client library seems to have been updated already. Please refer to the updated Quickstart page.

**Comment by kaerm** [comment]
Thanks @ryogok for the update I am closing this issue but feel free to open a new one if there are any follow ups.

**Comment by pyxploiter** [comment]
For version < 0.6.0
`from azure.cognitiveservices.vision.computervision.models import TextOperationStatusCodes`

For version >= 0.6.0
`from azure.cognitiveservices.vision.computervision.models import OperationStatusCodes`

You can do something like this to work it for both kind of versions:
```
try:
	# for < 0.6.0
	from azure.cognitiveservices.vision.computervision.models import TextOperationStatusCodes
except:
	# for >= 0.6.0
	from azure.cognitiveservices.vision.computervision.models import OperationStatusCodes
```

**Comment by atnjqt** [comment]
@pyxploiter is there an equivalent on version >= 0.6.0 (specifically, 0.7.0) for the `TextRecognitionMode`? I get an error as well, I have to rollback to 0.5.0

``` python
from azure.cognitiveservices.vision.computervision.models import TextRecognitionMode
```

**Comment by pyxploiter** [comment]
> @pyxploiter is there an equivalent on version >= 0.6.0 (specifically, 0.7.0) for the `TextRecognitionMode`? I get an error as well, I have to rollback to 0.5.0
> 
> ```python
> from azure.cognitiveservices.vision.computervision.models import TextRecognitionMode
> ```

`TextRecognitionMode` module is removed. The official documentation is also updated. If you want to extract the text from the image, you can refer to this:

https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision#get-text-from-image
