### ISSUE TITLE
python3.12 and azure-eventhub, synchronous client publish message throws: "azure.eventhub.exceptions.EventHubError: module 'ssl' has no attribute 'wrap_socket'"

### ISSUE THREAD

**Issue by erewokMF** [Azure/azure-sdk-for-python#32877]
- **Package Name**: `azure-eventhub`
- **Package Version**: `5.11.4` 
- **Operating System**: debian bookworm
- **Python Version**: 3.12.0

**Describe the bug**

Publishing a message using a synchronous Eventhub client throws an exception:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_client_base.py", line 582, in _do_retryable_operation
    return operation()
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_client_base.py", line 540, in _open
    self._handler.open(connection=conn)
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_pyamqp/client.py", line 324, in open
    self._connection.open()
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_pyamqp/_connection.py", line 817, in open
    self._connect()
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_pyamqp/_connection.py", line 205, in _connect
    self._transport.connect()
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_pyamqp/_transport.py", line 181, in connect
    self._init_socket(
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_pyamqp/_transport.py", line 317, in _init_socket
    self._setup_transport()
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_pyamqp/_transport.py", line 486, in _setup_transport
    self.sock = self._wrap_socket(self.sock, **self.sslopts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_pyamqp/_transport.py", line 493, in _wrap_socket
    return self._wrap_socket_sni(sock, **sslopts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_pyamqp/_transport.py", line 543, in _wrap_socket_sni
    sock = ssl.wrap_socket(**opts)  # pylint: disable=deprecated-method
           ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/partner_portal/endpoints/events.py", line 169, in auth_checker
    return fn(*args, event_list, log=log, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/partner_portal/endpoints/events.py", line 393, in post
    eventhub_client.send_event(
  File "/app/partner_portal/clients/eventhub.py", line 101, in send_event
    event_data_batch = self.client.create_batch(partition_key=partition_key)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_producer_client.py", line 739, in create_batch
    self._get_max_message_size()
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_producer_client.py", line 335, in _get_max_message_size
    )._open_with_retry()
      ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_producer.py", line 155, in _open_with_retry
    return self._do_retryable_operation(self._open, operation_need_param=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/azure/eventhub/_client_base.py", line 601, in _do_retryable_operation
    raise last_exception
azure.eventhub.exceptions.EventHubError: module 'ssl' has no attribute 'wrap_socket'
module 'ssl' has no attribute 'wrap_socket'
```

**To Reproduce**
1. Use Docker image `FROM python:3.12-slim as builder`
2. Publish a message
3. Check for error

**Expected behavior**
No exception

**Additional context**
Works fine on Python 3.11.*

**Comment by kashifkhan** [comment]
Thank you for the feedback @erewokMF . We will investigate and update this thread accordingly :)

**Comment by kashifkhan** [comment]
@erewokMF We have just released a new version of EH with the updated code :)

**Comment by erewokMF** [comment]
Thanks for letting me know! Cheers.
