### ISSUE TITLE
Missing ImportSource (and others) in azure.mgmt.containerregistry.v2019_04_01.models

### ISSUE THREAD

**Issue by elesel** [Azure/azure-sdk-for-python#18928]
- **Package Name**: azure-mgmt-containerregistry
- **Package Version**: 8.0.0
- **Operating System**: Ubuntu 18.04
- **Python Version**: 3.6

**Describe the bug**
A lot of classes were removed from azure.mgmt.containerregistry.v2019_04_01.models without an accompanying mention in release notes. Were these removals intentional?

**To Reproduce**
`from azure.mgmt.containerregistry.v2019_04_01.models import ImportSource`

**Expected behavior**
`ImportSource` should be found.

**Screenshots**
`ImportError: cannot import name 'ImportSources' from 'azure.mgmt.containerregistry.v2019_04_01.models'`

**Additional context**

**Comment by swathipil** [comment]
@elesel Thanks for your question! Directing this to the right people to get it answered.

**Comment by msyyc** [comment]
which version of 'azure-mgmt-containerregistry' do you use before?

**Comment by BigCat20196** [comment]
Hi @elesel, The `ContainerRegistry` has been updated to version 9.0.0. It is strongly recommended that you try the latest version, thank you.

pypi link: https://pypi.org/project/azure-mgmt-containerregistry/9.0.0/

**Comment by elesel** [comment]
`from azure.mgmt.containerregistry.v2019_04_01.models import ImportSource` still doesn't work in version 9.0.0, but I've been able to work around the issue. My concern was mainly that there wasn't mention of a breaking change in the release notes.

**Comment by BigCat20196** [comment]
Hi @elesel, actually, we prefer to use `from azure.mgmt.containerregistry.models import ImportSource`, which can avoid this issue.

In `v2019_ 04_01`,the missing model in version is caused by swagger breaking changes. In `v2019_ 05_01` This model was added back.

If you want the pin version, you can use the following:
```
from azure.mgmt.containerregistry.v2019_05_01.models import ImportSource
```

**Comment by elesel** [comment]
Thanks, @BigCat20196. Will do.
