### PR TITLE
Fix core auth

### PR DESCRIPTION
**Pull request by lmazuel**
Fix regression introduced in #10653 

The type ignore was necessary to avoid that:
> _authentication.py:93: error: Item "None" of "Optional[AccessToken]" has no attribute "token"

In this particular case, we could 1) type ignore, 2) use a cast 3) add an (unnecessary) check for None in the if to allow mypy to be certain it's not None. 

I don't like type ignore since we lose all benefits of typing.
Cast is better, but has the problem of disabling mypy and telling it "shut up we know the type", which may or may not be a problem if we refactor the code at some point.
The if is more explicit (and thus more zen) and has the advantage to be robust to refactoring, since mypy will complain again if those lines are touched

Being the name of the property `_need_new_token`, checking None doesn't seem stretched to me (even if I understand the property also check it)

### CODE REVIEW

File: sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py [hunk 1]
```diff
@@ -89,9 +89,9 @@ def on_request(self, request):
         """
         self._enforce_https(request)
 
-        if self._need_new_token:
+        if self._token is None or self._need_new_token:
             self._token = self._credential.get_token(*self._scopes)
```
Comment (xiangyan99) [inline sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py:93]: def _need_new_token(self):
        # type: () -> bool
        return not self._token or self._token.expires_on - time.time() < 300

Seems like self._token is None is not needed?

Comment (lmazuel) [reply sdk/core/azure-core/azure/core/pipeline/policies/_authentication.py:93]: It's unnecessary (see my PR description), but that's the only way to make mypy happy

**Comment by lmazuel** [comment]
Merging, for some reasons ADO didn't sent the event to Github, but everything's green
image
