### ISSUE TITLE
AttributeError: 'VirtualNetworksOperations' object has no attribute 'create_or_update'

### ISSUE THREAD

**Issue by hagh** [Azure/azure-sdk-for-python#16507]
- **Package Name**: azure-mgmt-network
- **Package Version**: 17.0.0
- **Operating System**: Windows
- **Python Version**: 3.6

**Describe the bug**
We are following this [example](https://docs.microsoft.com/en-us/python/api/overview/azure/network?view=azure-python#example) in our notebooks to create a virtual network, and it works fine with azure-mgmt-network==12.0.0, but on the latest version of the package, 17.0.0, we get the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-a5bdf60cec9c> in <module>
     18 network_client = NetworkManagementClient(ws._auth_object, subscription_id)
     19 
---> 20 async_vnet_creation = network_client.virtual_networks.create_or_update(
     21     resource_group,
     22     vnet_name,

AttributeError: 'VirtualNetworksOperations' object has no attribute 'create_or_update'

---------------------------------------------------------------------------

**To Reproduce**
1. Run the example linked above with the latest version of the package

**Expected behavior**
The example should work as is, or if things have changed the documentation and the example needs to be updated to reflect those changes.

**Screenshots**
N/A

**Additional context**
Link to notebook: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/reinforcement-learning/atari-on-distributed-compute/pong_rllib.ipynb

**Comment by lmazuel** [comment]
Hi @hagh 
I'm tagging the ML team to update the sample. In the meantime, all long running operations starts with `being_` now (begin_create_or_update)

CC @jsntcy

**Comment by hagh** [comment]
Hi @lmazuel,

Thanks for looking into this. I tried to use `begin_create_or_update` before submitting this issue, but looks like it needs additional input parameters, and without that additional input it fails down the stack. There is no example on how to use it to avoid those error.
Also according to documentation `begin_create_or_update` has been available with older versions as well. `create_or_update` sounds more like an alias, a wrapper, or a convenience method which is missing in the later versions (16.0.0. and 17.0.0). I could be wrong.

**Comment by v-strudm-msft** [comment]
Hello @lmazuel, please review for re-assignment to another product team. Thanks!

**Comment by lmazuel** [comment]
@v-strudm-msft I'm unsure why you removed the label I put :(. Please let me know on Teams if you disagree with them

**Comment by lmazuel** [comment]
@hagh sorry but you're incorrect, `begin_create_or_update` is the new nomenclature we renamed `create_or_update` from (I did the change myself in the code generator :p).

The new generic samples repo is here:
https://github.com/Azure-Samples/azure-samples-python-management

But I don't know if they have this scenario yet (CC @jsntcy @changlong-liu )

**Comment by jsntcy** [comment]
@hagh, please see code example here: https://github.com/Azure-Samples/azure-samples-python-management/blob/master/samples/network/virtual_network/manage_virtual_network.py#L37

**Comment by rubendv** [comment]
The documentation still mentions create_or_update: https://docs.microsoft.com/en-us/python/api/overview/azure/network?view=azure-python
