### ISSUE TITLE
azureml_artifacts_builder() got an unexpected keyword argument 'tracking_uri'

### ISSUE THREAD

**Issue by guybartal** [Azure/azure-sdk-for-python#43661]
- **Package Name**: azure-ai-ml==1.29.0, azureml-mlflow>=1.54.0, mlflow==3.5.0
- **Operating System**:  Ubuntu 24.04.2 LTS
- **Python Version**: 3.12

**Describe the bug**
Failed on `mlflow.log_artifact` with the following error:
`azureml_artifacts_builder() got an unexpected keyword argument 'tracking_uri'`

**To Reproduce**
1. add the packages above, create mlflow client with the tracking url from azure ml:
`mlflow.set_tracking_uri(mlflow_tracking_uri)`
1. call `mlflow.log_artifact` with a local path

**Expected behavior**
path content should be uploaded to azure ml as artifact

**Screenshots**

**Additional context**
Works on mlflow=3.0.0 failed when upgraded to latest (3.5.0)

might be related to #42626

**Comment by kshitij-microsoft** [comment]
What is the version of azureml-mlflow getting used here?

**Comment by guybartal** [comment]
@kshitij-microsoft, we used azureml-mlflow==1.60.0
it worked until mlflow==3.1.1, after this version the tracking url is broken. 
by the way:

```bash
$ uv add azureml-mlflow==1.60.0.post1
  × No solution found when resolving dependencies:
  ╰─▶ Because azureml-mlflow==1.60.0.post1 depends on mlflow-skinny<3.0.0 and mlflow==3.5.0 depends on mlflow-skinny==3.5.0, we can conclude that azureml-mlflow==1.60.0.post1
      and mlflow==3.5.0 are incompatible.
      And because your project depends on azureml-mlflow==1.60.0.post1 and mlflow==3.5.0, we can conclude that your project's requirements are unsatisfiable.
  help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip locking and syncin
```

**Comment by guybartal** [comment]
Hi @kshitij-microsoft, @jayesh-tanna and update on this?

**Comment by mpaguilar** [comment]
I'm getting the same error. Downgraded to 3.1.1, and it works.

**Comment by jayesh-tanna** [comment]
please use azureml-mlflow <= 1.60.0.post1 version in order to use mlflow < 3. This version has this restriction since April 2025.
Please use azureml-mlflow >= 1.61.0 in order to use mlflow > 3.
